language: c
sudo: false
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
      - DISTRO="ubuntu-16.04"
      - PACKAGE="dead_code_analyzer"
  matrix:
      - OCAML_VERSION=4.05
      - OCAML_VERSION=4.06
      - OCAML_VERSION=4.07
      - OCAML_VERSION=4.08
      - OCAML_VERSION=4.09
